apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: manufacturer-net-ca
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: manufacturer-net-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: manufacturer-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
 
    server:
      name: ca
      tlsstatus: true
      admin: manufacturer-admin 
  
    storage:
      storageclassname: manufacturersc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://20.110.161.253:8200
      authpath: localmanufacturer-net-auth
      secretcert: secretsv2/data/crypto/peerOrganizations/manufacturer-net/ca?ca.manufacturer-net-cert.pem
      secretkey: secretsv2/data/crypto/peerOrganizations/manufacturer-net/ca?manufacturer-net-CA.key
      secretadminpass: secretsv2/data/credentials/manufacturer-net/ca/manufacturer?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: none
      type: peer
      external_url_suffix: upgrade.upgrade.com
